# Generated by Django 3.0.8 on 2020-08-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20200812_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message_title',
            field=models.CharField(max_length=100),
        ),
    ]
