# Generated by Django 3.0.8 on 2020-08-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='location_link',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
