# Generated by Django 3.0.8 on 2020-08-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_has_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='location_link',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=254),
        ),
    ]
