# Generated by Django 3.0.8 on 2020-08-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200828_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='location_link',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
